[Variables]
Color1=255, 255, 255, 255
Color2=255, 255, 255, 160
Font=Trebuchet MS
Height1=10
Height2=7
TaskbarHeight=33
TaskbarWidth=450
CPUHistogramHeight=50
; CPUHistogramColor1=0,0,0,25
; CPUHistogramColor2=0,0,0,0
[StyleText]
X=40
Y=0
H=15
W=60
FontColor=#Color1#
FontFace=#Font#
FontSize=#Height1#
StringAlign=LEFT
StringStyle=NORMAL
AntiAlias=1
[StyleLabel]
X=r
Y=2r
H=15
W=60
FontColor=#Color2#
FontFace=#Font#
FontSize=#Height2#
StringAlign=RIGHT
StringStyle=NORMAL
AntiAlias=1
Postfix=" |"
UpdateDivider=1048576